docs/.vuepress/styles/index.styl, docs/README.md
=> Added demo link

docs/guide.md
=> Added documentation about virtualization config

docs/guide.md
=> Added user setup instructions for hpux

docs/guide-2.x.md
Depends on https://github.com/ercole-io/ercole-web/pull/312
=> Clarified optional steps

docs/ercole-agents.md
Update ercole-agents.md Oracle OLVM
=> Update ercole-agents.md Oracle OLVM

docs/ercole-agents.md
Update ercole-agents.md Oracle OLVM hostname
=> Update ercole-agents.md Oracle OLVM hostname

docs/installation.md
=> Load NGINX modular configuration file

docs/ercole-agents.md
=> Added SQLServer section

docs/ercole-agents.md
=> Added MySQL section

docs/ercole-agents.md
=> Added PostgreSQL section

docs/.vuepress/config.js, docs/ercole-cloud.md
=> Added ercole cloud section

docs/ercole-cloud.md
=> Added Oracle Cloud section

docs/ercole-cloud.md
=> AWS doc changed

docs/ercole-agents.md, docs/ercole.md
Use hostdata period for FreshnessCheckJob
=> Use hostdata period for FreshnessCheckJob

docs/ercole-agents.md
Use hostdata period for FreshnessCheckJob part 2
=> Use hostdata period for FreshnessCheckJob part 2

docs/ercole.md
=> Changed LDAP Section

docs/ercole-agents.md
Resolve #139 Added Oratab helpers command
=> Added Oratab helpers command

docs/ercole-agents.md
Resolve #141 Change info for Windows installation
=> Change info for Windows installation

docs/ercole-agents.md
Resolve #143 Add DEB information in agent section
=> Add DEB information in agent section

docs/ercole.md
=> Image test

docs/ercole.md
Authentication and authorization
=> Authentication and authorization

docs/ercole.md
=> Repository api yum

docs/ercole-agents.md
Update windows agent documentation
=> Update windows agent documentation

docs/ercole-agents.md
Resolve #151 Added MongoDB section
=> Added MongoDB section
